version: '3.8'
services:
  db:
    container_name: mysql_db
    image: mysql
    ports:
      - 3306:3306
    restart: always
    networks:
      - backend-local-networks
    environment:
      MYSQL_ROOT_PASSWORD: admin123456.
      MYSQL_DATABASE: internet-banking
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123456.
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 9081:8080
    networks:
      - backend-local-networks
networks:
  backend-local-networks:
volumes:
  mysql_data:
